### ISSUE TITLE
Can't load lines

### ISSUE THREAD

**Issue by 0xFF3** [D4Vinci/One-Lin3r#18]
Hello. I installed the one-lin3r through python -m pip install on windows 10. I run from here "C: \ py372 \ Scripts \". The error on the screenshot. Apparently the program can not find a directory with resources. I tried to copy it to the same directory from which I launch one-lin3r, but the error remains.
![изображение](https://user-images.githubusercontent.com/35723760/60150269-604bbe80-97f1-11e9-98e6-6102cd28f4c4.png)

**Comment by hotelzululima** [comment]
ditto on hi sierra osx

**Comment by D4Vinci** [comment]
try installing it with the github method and tell me the result.
Also there's hidden command called `debug` using it will show the error message

**Comment by 0xFF3** [comment]
Hi. I try use install method for github, but the error remains.
![изображение](https://user-images.githubusercontent.com/35723760/60236101-90639200-98c3-11e9-98fd-7ea2da1c65fa.png)

**Comment by gh0st91** [comment]
Have you tried running `pip3 check one-lin3r`? If it returns with an unmet dependency, install it using `pip3 install [dependency]`

**Comment by D4Vinci** [comment]
Just pushed the new version fixing this issue, 21 new liners, and more things.
Please reopen if this problem persists.
