### ISSUE TITLE
Problem at install

### ISSUE THREAD

**Issue by Orbit110** [D4Vinci/One-Lin3r#21]
Hello, i have the new kali linux version which offers windows style.

when i install with pip or git clone it i cannot start even i have the requirements.
It says:  

"root@ORBIT:~# one-lin3r
Traceback (most recent call last):
  File "/usr/local/bin/one-lin3r", line 6, in <module>
    from one_lin3r.main import main
  File "/usr/local/lib/python2.7/dist-packages/one_lin3r/main.py", line 3, in <module>
    from .core import Cli
  File "/usr/local/lib/python2.7/dist-packages/one_lin3r/core/Cli.py", line 6, in <module>
    from . import utils,db
  File "/usr/local/lib/python2.7/dist-packages/one_lin3r/core/utils.py", line 5, in <module>
    from prompt_toolkit.shortcuts import CompleteStyle, prompt
ImportError: cannot import name CompleteStyle"

How i can solve this. Really nice program by the way. :)

**Comment by gh0st91** [comment]
I am having the same exact error. When I uninstall the package and reinstall it pip3 tells me that the dependencies are already satisfied. I ran pip3 check on one-lin3r and installed deps that check found not properly met. Screenshot attached
![Screenshot (67)](https://user-images.githubusercontent.com/37459473/72568955-15b59080-386e-11ea-8dd5-8b87fdaee621.png)

**Comment by gh0st91** [comment]
This issue has already been fixed. I really gotta start looking at the closed issues first...
Here is the link to the solution. It worked wonders for me. [https://github.com/D4Vinci/One-Lin3r/issues/19](url) You just have to force reinstall prompt-toolkit using `pip3 install prompt-toolkit --force-reinstall` and one-lin3r should work no problem.
Mods - close this thread please.

**Comment by D4Vinci** [comment]
try this command:
`pip3 install prompt-toolkit --force-reinstall`
it solved this error for other people, it looks like it's a problem with the 'prompt-toolkit' module installation.
Reopen if the problem persists
