### ISSUE TITLE
Advice: pip install readline  error

### ISSUE THREAD

**Issue by KunPengRen** [D4Vinci/One-Lin3r#8]
Befor pip install readlin ,should use command sudo apt-get install libncurses5-dev.That tooken me much time....

**Comment by medoix** [comment]
Not sure why you closed this, this should be in the instructions. Spent ages trying to figure it out before thinking to look at closed issues. Thanks!

**Comment by D4Vinci** [comment]
Then I will add it to the instructions!
Thanks very much!
