### ISSUE TITLE
Sometime it would echo  payload not found!

### ISSUE THREAD

**Issue by KunPengRen** [D4Vinci/One-Lin3r#9]
I use command list it would echo the payload，but when I use info or use command it would echo payload not found！this issue occured when I using the tools some minutes ago。while，i reboot the computer，it missing，and after some minutes，it began。

**Comment by D4Vinci** [comment]
Is the problem remain ? Any more details !?

**Comment by D4Vinci** [comment]
Okay, reopen if you care !
